version: "3.8"

services:
  bakugan:
    container_name: bakugan
    build: ./service
    ports:
      - "8100:8100"
    volumes:
      - ./service/:/usr/src/app/
    env_file:
      - ./.env.dev
    links:
      - "db:db"
  db:
    container_name: postgres-0
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=pimat
      - POSTGRES_PASSWORD=pimat
      - POSTGRES_DB=bakugan_db

volumes:
  postgres_data: